---
- hosts: localhost
  collections:
  - netapp.ontap
  gather_facts: no
  name: Destination Cluster Config
  vars:
      state: present
  vars_files:
  - standard_platform_vars.yml
  - specific_config_vars.yml

  tasks:

  # ROLE: netapp.ontap collections
  #   na_ontap_config_cluster - Day1
  #   na_ontap_vserver_create - Day1

  roles:
  - na_ontap_cluster_config
  - na_ontap_vserver_create

  tasks:
    
  ###
  # Standard Cluster configuration section
  ###

  # Nothing here - Managed seperately
    
  ###
  # Standard SVM configuration section
  ###
  
  # Nothing here - Managed seperately
  