---
- hosts: localhost
  collections:
  - netapp.ontap
  gather_facts: no
  name: Destination Cluster Config
  vars:
      state: present
  vars_files:
  - standard_platform_vars.yml
  - specific_config_vars.yml

  tasks:

  # ROLE: netapp.ontap collections
  #   na_ontap_config_cluster - Day1
  #   na_ontap_vserver_create - Day1

  roles:
  - na_ontap_cluster_config
  - na_ontap_vserver_create

  tasks:
    
  ###
  # Standard Cluster configuration section
  ###

    
  ###
  # Standard SVM configuration section
  ###
  
  # non-ROLE: Update default NFS Server configuration
  
  #  - name: Manage NFS
  #    na_ontap_nfs:
  #      state: "{{ state }}"
  #      service_state: started
  #      vserver: "{{ SVM }}"
  #      nfsv3: enabled
  #      nfsv4: disabled
  #      nfsv41: disabled
  #      tcp: enabled
  #      udp: disabled
  #      vstorage_state: disabled
  #      <<: *login
  
  # Managing Export-policies
  
    - name: Create Data SVM Export-policy
      na_ontap_export_policy:
        state: "{{ state }}"
        name: "{{ svm_export_policy_name }}"
        vserver: "{{ svm }}"
        hostname: "{{ hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
        validate_certs: false
    - name: Setup "Default" and SVM Export-policies
      na_ontap_export_policy_rule:
        state: "{{ state }}"
        policy_name: "{{ item.name }}"
        vserver: "{{ svm }}"
        client_match: "{{ item.client_match }}"
        ro_rule: "{{ item.ro_rule }}"
        rw_rule: "{{ item.rw_rule }}"
        rule_index: "{{ item.rule_index }}"
        super_user_security: "{{ item.super_user_security }}"
        hostname: "{{ hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
        validate_certs: false
      with_items: "{{ export_policy_rules_list }}"