---
- hosts: localhost
  collections:
  - netapp.ontap
  gather_facts: no
  name: Cluster Config
  vars:
    state: present
  vars_files:
  - std_cluster_config_vars.yml

  roles:
  - na_ontap_cluster_config

  