---
- hosts: localhost
    gather_facts: false
    vars_files:
    - test_vars.yml
    collections:
    - netapp.ontap
    tasks:
    - name: Display ONTAP_info: All 
      na_ontap_info:
        state: info
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
        validate_certs: false
      register: ontap_info
      - debug:
          msg: "{{ ontap_info.ontap_info }}"