---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    state:  "{{ state }}"
    svm:    ontap-vs01
    export_policy_name: default
    client_match: "{{ client_match }}"
    ro_rule:      "{{ ro_rule }}"
    rw_rule:      "{{ rw_rule }}"
    rule_index:   "{{ rule_index }}"
    super_user:   "{{ super_user }}"

  tasks:

  # Manage Export-policies - Create 'data' policy
  - name: '{{ Create if state == present else Delete }} Data SVM Export-policy'
    netapp.ontap.na_ontap_export_policy:
      state: "{{ state }}"
      name: "{{ export_policy_name }}"
      vserver: "{{ svm }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      when: state == 'present'

  # Manage Export-policies - Add rules
  - name: '{{ Add if state == present else Remove }} Data SVM Export-policy rules'
    netapp.ontap.na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: "{{ export_policy_name }}"
      vserver: "{{ svm }}"
      client_match: "{{ client_match }}"
      rule_index: "{{ rule_index }}"
      ro_rule: "{{ ro_rule }}"
      rw_rule: "{{ rw_rule }}"
      super_user_security: "{{ super_user }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

  # Manage Export-policies - Create 'data' policy
  - name: '{{ Create if state == present else Delete }} Data SVM Export-policy'
    netapp.ontap.na_ontap_export_policy:
      state: "{{ state }}"
      name: "{{ svm_export_policy_name }}"
      vserver: "{{ svm }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    when: state == 'absent'
