---
- hosts: localhost
  gather_facts: false
  vars:
      state: "{{ state }}"
  tasks:
    
  - name: Manage NFS Settings
    na_ontap_nfs:
      state: "{{ state }}"
      service_state: started
      vserver: "{{ SVM }}"
      nfsv3: enabled
      nfsv4: disabled
      nfsv41: disabled
      tcp: enabled
      udp: disabled
      vstorage_state: disabled
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false