---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
      netapp_hostname: 192.168.7.200
      state: present
      service_state: started
      svm:    ontap-vs01
      nfsv3:  enabled
      nfsv4:  enabled
      nfsv41: enabled
      showmount: enabled
      tcp:    enabled
      tcp_max_xfer_size : 65536
      udp:    disabled
      vstorage_state: disabled
      
  tasks:

  - name: Manage NFS Settings
    na_ontap_nfs:
      state: "{{ state }}"
      service_state: "{{ service_state }}"
      vserver: "{{ svm }}"
      nfsv3: "{{ nfsv3 }}"
      nfsv4: "{{ nfsv4 }}"
      nfsv41: "{{ nfsv41 }}"
      showmount: "{{ showmount }}"
      tcp: "{{ tcp }}"
      tcp_max_xfer_size: "{{ tcp_max_xfer_size }}"
      udp: "{{ udp }}"
      vstorage_state: "{{ vstorage_state }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
