- hosts: localhost
  name: ONTAP Volume Snapshot Management
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    netapp_hostname: 192.168.7.190
    state:    present
    vserver:  vs01
    volname:  ansibleVolume
    comment:  
    snapshot_name: 
    from_name: 
    expiry_time: 
    
  tasks:

  - name: "{{ tower_job_template_name }}"
    netapp.ontap.na_ontap_snapshot:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

      state:      "{{ state }}"
      vserver:    "{{ vserver }}"
      volume:     "{{ volname }}"
      snapshot:   "{{ snapshot_name }}"
      from_name:  "{{ from_name }}"
      comment:    "{{ comment }}"
      expiry_time: "{{ expiry_time }}"


