---
- hosts: localhost
  name: "ONTAP Cluster Config: {{ cluster.name }}"
  gather_facts: no
  collections:
  - netapp.ontap
  
  vars_files:
  - vars/vars_files.yml
  # vars_prompt:  # For NetApp Admin Credentials
  #   - name: netapp_username
  #     prompt: NetApp 'admin'
  #   - name: netapp_password
  #     prompt: NetApp 'admin' password
  #     secret: true
  vars:
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    state:    present
    netapp_hostname: 192.168.7.190
    svm:      ansible_vserver
    aggrname: 
    volname:  ansibleVolume
    junction: 
    space_guarantee: none
    ss_policy: default
    export_policy: 
    e_policy:
    tiering_policy: 
    aqos_policy:
    unix_permissions: ---rwxr-xr-x  # unix_permissions: 777

    fg:
      name: fg_auto_01
      size: 200
      size_unit: tb

  tasks:

  ###
  # Flexgroup: Autoprovision
  ###

  - name: Create Flexgroup volume auto provsion as flex group
    na_ontap_volume:
      <<: *login
      
      state:              "{{ state }}"
      vserver:            "{{ svm }}"
      junction_path:      "/{{ junction if junction else volname }}"
      space_guarantee:    "{{ space_guarantee | default('none') }}"
      
      snapshot_policy:    "{{ ss_policy | default('default') }}"
      policy:      "{{ export_policy | default('default') }}"
      # export_policy:      "{{ export_policy | default('default') }}"
      tiering_policy:     "{{ tiering_policy | default('omit')  }}"
      efficiency_policy:  "{{ e_policy | default('omit')  }}"
      unix_permissions:   "{{ unix_permissions | default('omit')  }}"
      qos_adaptive_policy_group: "{{ aqos_policy | default('none')  }}"


      name:               "{{ fg.name }}"
      auto_provision_as:  flexgroup
      size:               "{{ fg.size }}"
      size_unit:          "{{ fg.size_unit }}"
