- hosts: localhost
  name: ONTAP Volume Management
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    netapp_hostname: 192.168.7.190
    state: present
    vserver: ansible_vserver
    aggrname: source_01_aggr1
    volname: ansibleVolume
    size: 1
    size_unit: gb
    junction_path: "/{{ volname }}"
    e_policy:
    aqos_policy:
    export_policy:
    unix_permissions: ---rwxr-xr-x
    
  tasks:
  - name: "{{ tower_job_template_name }}"
    netapp.ontap.na_ontap_volume:
      state: "{{ state }}"
      name: "{{ volname }}"
      aggregate_name: "{{ aggrname }}"
      size: "{{ size }}"
      size_unit: "{{ size_unit }}"
      policy: "{{ export_policy | default('default') }}"
      junction_path: "/{{ volname if not junction_path else volname }}"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      unix_permissions: "{{ unix_permissions }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      efficiency_policy: "{{ e_policy }}"
      qos_adaptive_policy_group: "{{ aqos_policy }}"
