---
- hosts: localhost
  collections:
  - netapp.ontap
  gather_facts: no
  name: Vserver Config
  vars:
    state: present
  vars_files:
  - vars/std_vserver_config_vars.yml

  roles:
  - na_ontap_vserver_create

  
